GET {{host}}/sheets

###

GET {{host}}/sheets/1FFWIDHigL5uztBEAxVaVUpywgp9WPy4Wo3XI5EFKBug?range=Sheet2!A1:J20

###

POST {{host}}/sheets/1FFWIDHigL5uztBEAxVaVUpywgp9WPy4Wo3XI5EFKBug?range=Sheet2!A1:J20
Content-Type: application/json

{
  "values": [
    ["Name", "Relationship", "Birth District"],
    ["Rafia", "Niece", "Dinajpur"],
    ["Atif", "Nephew", "Dhaka"],
    ["Ahnaf", "Nephew", "Dinajpur"],
    ["Ayesha", "Niece", "Dinajput"],
    ["Arham", "Nephew", "Dhaka"],
    ["Arwa", "Niece", "Dhaka"]
  ]
}

###